[package]
name = "oidn-cmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.4"
exr = "1.72.0"
glob = "0.3.1"
hashbrown = "0.14.5"
oidn = "2.2.3"
snailquote = "0.3.1"
unescape = "0.1.0"
